#  Introduction to Python for Data Science - Exercises 14/9 #


The following are exercises for the Introduction to Python for Data Science course, module 2. Try to get through as many as you can, but do not despair if you cannot get through them all within the time frame.

## Part 1: Numpy

### Exercise 1 ###
Make sure you have numpy, pandas and matplotlib installed. Import them in the below codebox to be used in the rest of the notebook

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Exercise 2: Random 2D Points ###
Use Numpy to generate 20 random points in 2D

In [21]:
np.random.seed(10)
points = np.random.random((2,20))
print(points)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
  0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
  0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
  0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317 0.43401399
  0.61776698 0.51313824 0.65039718 0.60103895 0.8052232  0.52164715
  0.90864888 0.31923609 0.09045935 0.30070006 0.11398436 0.82868133
  0.04689632 0.62628715]]


Use numpy to find the mean and standard deviation of the points

In [31]:
print(np.mean(points,axis=1))
print(np.std(points,axis=1))
print(np.min(points,axis=1))

[0.51699473 0.47760706]
[0.30005152 0.24493163]


### Exercise 3: Arrays
Create a two dimensional numpy array, then print number of dimensions, the shape and the number of elements

In [43]:
points = np.ones((2,20))
points2 = np.array(([0,22,23],[1,2,3],[1,2,3]))
reg_array = [[0,22,23],[1,2,3],[1,2,3]]
print(type(points2))
print(type(reg_array))
print(np.mean(reg_array,axis=1))
print(points2)

<class 'numpy.ndarray'>
<class 'list'>
[15.  2.  2.]
[[ 0 22 23]
 [ 1  2  3]
 [ 1  2  3]]


### Exercise 4: Elementwise operations
In an numpy array (you can just reuse from previous exercise), take the square root of each element, take it as the exponent and multiply them by a constant number

In [50]:
points = np.ones((2,20))
points[0,4] = 6

points = np.sqrt(points)*10
print(points)

[[10.         10.         10.         10.         24.49489743 10.
  10.         10.         10.         10.         10.         10.
  10.         10.         10.         10.         10.         10.
  10.         10.        ]
 [10.         10.         10.         10.         10.         10.
  10.         10.         10.         10.         10.         10.
  10.         10.         10.         10.         10.         10.
  10.         10.        ]]


### Exercise 5: Matrix
Create two matrices and then compute the dotwise product (be aware of the matrix shapes)

In [64]:
A = np.random.random((5,3))
B = np.random.random((5,3))
print(A)
print(B)
print(f'{A.T @ B}')
print(np.dot(A.T,B))

[[0.51678928 0.62614367 0.50505912]
 [0.90966258 0.41330466 0.53546872]
 [0.34264313 0.12957678 0.66282175]
 [0.93567    0.61272918 0.8427385 ]
 [0.21790844 0.90317174 0.00976998]]
[[0.22581273 0.13205513 0.90754295]
 [0.91023064 0.58105791 0.08749305]
 [0.11687944 0.77107126 0.73279527]
 [0.08712836 0.3574632  0.77321162]
 [0.1314716  0.53783243 0.75472357]]
[[1.09492044 1.31267939 1.68761643]
 [0.70486615 1.12753554 1.85478113]
 [0.75362994 1.19541939 1.64991411]] 



[[1.09492044 1.31267939 1.68761643]
 [0.70486615 1.12753554 1.85478113]
 [0.75362994 1.19541939 1.64991411]]


### Exercise 6: Search
Check with numpy for all unique places, and then pick one and print the array with boolean values if it matches your choice or it doesn't

In [5]:
places = np.array(["Aarhus", "Copenhagen", "Aalborg", "Aarhus", "Odense", "Aalborg", "Aarhus"])

### Exercise 7: Indexing
Use both the matching and the negation of the fitting place names from last exercise as an index for the random array in this exercise

In [11]:
data = np.random.rand(7,2)

[[0.21533991 0.32040005]
 [0.52421668 0.03976608]
 [0.34500988 0.85131779]]


## Part 2: Pandas

### Exercise 8: The Pokemon Dataset ###

##### Task 1
Use pandas to load the dataset Pokemon.csv. Output the first 10 rows of the dataset.

In [112]:
poke = pd.read_csv("../data/Pokemon.csv")
poke

#                   Name   Type_1  Type_2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

##### Task 2

Find all legendary pokemons in the data set

In [129]:
poke2 = poke.loc[(poke["Type_1"]=='Fire') ^ ~(poke['Legendary']) ]
poke2.loc[(poke2["Type_1"]=='Fire') & (poke2['Legendary']) ]

#       Name Type_1  Type_2  Total   HP  Attack  Defense  Sp. Atk  \
158  146    Moltres   Fire  Flying    580   90     100       90      125   
263  244      Entei   Fire     NaN    580  115     115       85       90   
270  250      Ho-oh   Fire  Flying    680  106     130       90      110   
542  485    Heatran   Fire   Steel    600   91      90      106      130   
799  721  Volcanion   Fire   Water    600   80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
158       85     90           1       True  
263       75    100           2       True  
270      154     90           2       True  
542      106     77           4       True  
799       90     70           6       True

##### Task 3

Find the minimum, maximum and average Speed

In [81]:
print(poke["Speed"].mean())
print(poke["Speed"].max())
print(poke["Speed"].min())
print(poke["Speed"].median())
poke.describe()


68.2775
180
5
65.0


#      Total          HP      Attack     Defense     Sp. Atk  \
count  800.000000  800.00000  800.000000  800.000000  800.000000  800.000000   
mean   362.813750  435.10250   69.258750   79.001250   73.842500   72.820000   
std    208.343798  119.96304   25.534669   32.457366   31.183501   32.722294   
min      1.000000  180.00000    1.000000    5.000000    5.000000   10.000000   
25%    184.750000  330.00000   50.000000   55.000000   50.000000   49.750000   
50%    364.500000  450.00000   65.000000   75.000000   70.000000   65.000000   
75%    539.250000  515.00000   80.000000  100.000000   90.000000   95.000000   
max    721.000000  780.00000  255.000000  190.000000  230.000000  194.000000   

          Sp. Def       Speed  Generation  
count  800.000000  800.000000   800.00000  
mean    71.902500   68.277500     3.32375  
std     27.828916   29.060474     1.66129  
min     20.000000    5.000000     1.00000  
25%     50.000000   45.000000     2.00000  
50%     70.000000   65.000000     3.00000  
75%     90.000000   90.000000     5.00000  
max    230.000000  180.000000     6.00000

##### Task 4

Compare the mean HP of the different primary types

In [123]:
poke = pd.read_csv("../data/Pokemon.csv")
poke.groupby("Type_2",dropna=False)["HP"].median()

Type_2
Bug         45.0
Dark        70.0
Dragon      79.0
Electric    87.5
Fairy       57.0
Fighting    80.0
Fire        67.5
Flying      70.0
Ghost       59.0
Grass       60.0
Ground      75.0
Ice         90.0
Normal      62.0
Poison      60.0
Psychic     70.0
Rock        65.0
Steel       70.0
Water       65.0
NaN         65.0
Name: HP, dtype: float64

##### Task 5

Some Pokemons have no secondary type. We don't want NaN in our DataFrame (it may give nasty errors!) so replace these instances with "NA" (Not Applicable).

In [116]:
poke = pd.read_csv("../data/Pokemon.csv")
poke["Type_2"] = poke["Type_2"].fillna(10)
poke

#                   Name   Type_1  Type_2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire      10    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

##### Task 6
Rename the 'Speed' column to 'movement'

In [109]:
poke = pd.read_csv("../data/Pokemon.csv")
poke = poke.rename(columns={'Speed': "Movement", 'HP':'Health'}, inplace=True)
poke

### Exercise 9: Merging two DataFrames ###
Below are two DataFrames of albums. Merge them into one DataFrame, that has two coloumns: "name" and "year".

In [ ]:
floyd_albums = pd.DataFrame({
    "album": ["Atom Heart Mother", "The Dark Side of the Moon", "Wish You Were Here", "The Wall"],
    "year": [1970,1973,1975,1979]
})

crimson_albums = pd.DataFrame({
    "name": ["In The Court of the Crimson King","Lizard", "Larks' Tongues in Aspic", "Red", "Discipline"], 
    "released": [1969, 1970, 1973, 1974, 1981]
})

### YOUR CODE HERE ###

## Part 3: Matplotlib

### Exercise 10: Random 2D Points ###
Use Numpy to generate 20 random points in 2D, and plot them using matplotlib

### Exercise 11: Plot Pokemeon
Make a bar plot of the number of pokemons in each generation

### Exercise 12: Plot Albums
Create a pie chart of the amount of albums released per year from exercise 9

### Exercise 13: Wine Dataset
First run the code below, then print a plot of the points with the 'sulphates' and 'alcohol' columns. Color the two different qualities 4 and 8 differently

In [21]:
wq = pd.read_csv("../data/winequality-red.csv", sep=';')
toy = wq[wq['quality'].isin([4, 8])].sample(n=20)

### Exercise 14: Design

##### Task 1
Write a code to plot the given two lines with different styles.

In [27]:
# line 1 points
x1 = [10,20,30]
y1 = [20,40,10]
# line 2 points
x2 = [10,20,30]
y2 = [40,10,30]

##### Task 2
Write a code to plot the given two lines with different styles and set the markers, then plot also just the markers

##### Task 3
Add labels descriptions to the two lines and a title for the plot

##### Task 4
Give the plot a grid

### Exercise 15: Flags with matplot
The code below calculates an outer product that, when plottet, resembles the Danish flag. Find two vectors which outer product resembles the Austrian flag

In [ ]:
v = np.array([1.0, 1.0, 0.0, 1.0, 1.0])
w = np.array([1.0, 1.0, 0.0, 1.0, 1.0, 1.0])
plt.matshow(np.outer(v, w), cmap='Reds', clim=(0, 1.5))